main: "net.proxworld.regions.RegionPlugin"
name: "prox-regions"
version: "1.0-SNAPSHOT"

libraries:
  - 'it.unimi.dsi:fastutil:8.5.6'
  - 'com.github.ben-manes.caffeine:caffeine:3.0.0'
  - 'org.apache.commons:commons-lang3:3.12.0'

#- 'net.kyori:adventure-platform-paper:4.0.0'
#- 'net.kyori:adventure-text-serializer-plain:4.0.0'
#  - 'com.zaxxer:HikariCP:4.0.3'
#  - 'org.jdbi:jdbi3-core:3.45.1'
#  - 'org.jdbi:jdbi3-sqlobject:3.45.1'
#  - 'org.jdbi:jdbi3-caffeine-cache:3.45.1'

api-version: 1.16
depend: [ "prox-api", "WorldGuard", "DecentHolograms" ]