blocks:
  1:
    item:
      type: GOLD_BLOCK
      name: "Регионы для Дмитриуса"
    size: 13 # 13x13x13
    abilities:
      - "HIDDEN"
    flags: [ ]
settings:
  # Формат регионов ({id} - айдишник региона)
  region-name-format: "region_block_{0}"

  # Включить ли молнию при создании
  lightning-on-create: true

  # Включить ли взрыв регионов
  region-explosion: true

  allowed-worlds:
    - "world"
    - "world_nether"

  # Включить ли то, если ставить блок на ШИФТе
  # то он будет ставиться как обычный блок
  place-region-block-by-shift: false

  # Голограмма с регионом
  hologram:
    enabled: true
    height: 1.5
    lines:
      - "Регион {region}"
      - "Владелец: {owner}"
limits:
  default-limit: 1
messages:
  region_create_error: "При создании региона возникла ошибка!"
  region_create_success: "Регион # успешно создан!"
  region_already_exists: "Ваш регион пересекается с другим!"