blocks:
  1:
    item:
      type: GOLD_BLOCK
      name: "Регионы для Дмитриуса"
    size: 13 # 13x13x13
    abilities:
      - "HIDDEN"
    flags: [ ]
settings:
  # Включить ли молнию при создании
  lightning-on-create: true

  allowed-worlds:
    - "world"
    - "world_nether"

  # Включить ли то, если ставить блок на ШИФТе
  # то он будет ставиться как обычный блок
  place-region-block-by-shift: false

  # Голограмма с регионом
  hologram:
    enabled: true
    height: 1.5
    lines:
      - "Регион {region}"
      - "Владелец: {owner}"

limits:
  default-limit: 1